DW\UserBundle\Entity\Role:
  type: entity
  repositoryClass: DW\UserBundle\Repository\RoleRepository
  table: role
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
    role:
      type: string
  manyToMany:
    users:
      targetEntity: DW\UserBundle\Entity\User
      mappedBy: roles