# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        DW\UserBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            entity:
                class: DW\UserBundle\Entity\User
                property: username
        oauth_provider:
            id: dw.oauth_user_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:    ^/
            anonymous: ~
            oauth:
                remember_me: true
                resource_owners:
                    facebook:           "/login/check-facebook"
                login_path:        /social/login
                use_forward:       false
                failure_path:      /social/login
                oauth_user_provider:
                    service: dw.oauth_user_provider
                default_target_path: /
            form_login:
                login_path:  login
                check_path:  login_check
                default_target_path: /
                always_use_default_target_path: true
            logout:
                path:   logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect/facebook, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }